#!/usr/bin/env node
/*
 * convertHtml.js - converts JSON files generated by webOSJsonFormatter
 *               into HTML reports and produces an overall Total Summary page.
 *
 * Copyright (c) 2026 JEDLSoft
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import path from 'node:path';
import fs from 'fs';
import OptionsParser from 'options-parser';

// Constants
const DEFAULT_OUTPUT_DIR = './';
const TOTAL_RESULT_FILENAME = '0.total-result.html';

// Option configuration
const optionConfig = {
    files: {
        short: 'f',
        varName: 'f',
        help: 'Specify files'
    },
    directory: {
        short: 'd',
        varName: 'directory',
        help: 'Directory where JSON files are located'
    },
    outputDirectory: {
        short: 'o',
        varName: 'output folder',
        help: 'Folder where output HTML files will be generated.'
    },
    outputFileName: {
        short: 'name',
        varName: 'output file name',
        help: 'Specify output HTML file name'
    },
    errorsOnly: {
        short: 'e',
        flag: true,
        default: false,
        help: 'Only return errors and suppress warnings'
    }
};

// Parse options
const options = OptionsParser.parse(optionConfig).opt;
const errorsOnly = options.errorsOnly ?? false;
const outDir = options.outputDirectory || DEFAULT_OUTPUT_DIR;

let totalSummary = [];

// Ensure output directory exists
ensureOutputDirectory(outDir);

// Entry point
if (options.files) console.log("File input is not implemented yet.");
if (options.directory) processDirectory(options.directory);

/* ----------------------------------------
 * HTML Escape Helper
 * --------------------------------------*/
function escapeHtml(str) {
    if (typeof str !== 'string') return str;
    return str
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#39;");
}

/* ----------------------------------------
 * Directory Processing
 * --------------------------------------*/
function ensureOutputDirectory(directory) {
    if (!fs.existsSync(directory)) {
        fs.mkdirSync(directory, { recursive: true });
    }
}

function processDirectory(dir) {
    try {
        const stat = fs.statSync(dir);
        if (!stat.isDirectory()) throw new Error("Invalid directory");
        walkDirectory(dir);
        writeTotalSummaryResult(totalSummary);
    } catch (err) {
        console.error(`Directory error: ${err.message}`);
        process.exit(1);
    }
}

function walkDirectory(dir) {
    const files = fs.readdirSync(dir);
    for (const file of files) {
        const fullPath = path.join(dir, file);
        if (fullPath.includes(".git")) continue;
        const stat = fs.statSync(fullPath);
        if (stat.isDirectory()) {
            walkDirectory(fullPath);
        } else if (file.toLowerCase().endsWith('.json')) {
            convertToHtml(fullPath);
        }
    }
}

/* ----------------------------------------
 * HTML Summary Generation
 * --------------------------------------*/
function writeTotalSummaryResult(sumJsonData) {
    const sorted = [...sumJsonData].sort((a, b) => a.name.localeCompare(b.name));
    const html = [
        getHeader("Summary of all app results"),
        getHtmlStyle(),
        getScript("case-filter.js"),
        buildTotalSummaryTable(sorted),
        getFooter()
    ].join('');

    fs.writeFileSync(path.join(outDir, "total-result.json"), JSON.stringify(sorted, null, 2), 'utf8');
    fs.writeFileSync(path.join(outDir, TOTAL_RESULT_FILENAME), html, 'utf8');
}

function buildTotalSummaryTable(data) {
    let count = 0;
    const rows = data.map(item => {
        const ruleInfo = buildRuleInfo(item.details);
        const nameColumn =
            item.errors === 0 && item.warnings === 0
                ? escapeHtml(item.name)
                : `<a href="./${escapeHtml(item.name)}-result.html">${escapeHtml(item.name)}</a>`;

        //Add the 'no-issues' class to entries that have no errors or warnings
        const rowClass = (item.errors === 0 && item.warnings === 0) ? 'no-issues' : '';

        return `
        <tr class="${rowClass}">
            <td class="highlight2">${++count}</td>
            <td class="highlight">${nameColumn}</td>
            <td class="highlight2 red">${item.errors}</td>
            <td class="highlight2 orange">${item.warnings}</td>
            <td class="highlight2">${ruleInfo}</td>
        </tr>`;
    }).join('');

    return `
<body>
<h1>Summary of all app results</h1>
<hr>
<label><input type="checkbox" id="toggleNoIssues"> Showing only cases with errors/warnings</label>
<table><thead>
<tr>
  <td class="highlight cell-bg"></td>
  <td class="highlight cell-bg">Name</td>
  <td class="highlight cell-bg">Errors</td>
  <td class="highlight cell-bg">Warnings</td>
  <td class="highlight cell-bg">Details</td>
</tr>
${rows}
</thead></table>`;
}

function buildRuleInfo(details) {
    if (!details) return '';
    return Object.entries(details)
        .map(([rule, count]) => `${escapeHtml(rule)} [ ${count} ]<br>`)
        .join('');
}

/* ----------------------------------------
 * JSON → Individual HTML Generator
 * --------------------------------------*/
function convertToHtml(jsonFile) {
    try {
        const json = JSON.parse(fs.readFileSync(jsonFile, 'utf-8'));
        const summary = createSummaryInfo(json.summary);

        if (json.summary.score !== 100) summary.details = countRuleViolations(json.details);

        totalSummary.push(summary);
        generateHtmlOutput(json, summary);

    } catch (err) {
        console.error(`Error in ${jsonFile}: ${err.message}`);
    }
}

function createSummaryInfo(summary) {
    return {
        name: summary.projectName,
        errors: summary.resultStats.errors,
        warnings: summary.resultStats.warnings
    };
}

function countRuleViolations(details) {
    return details.reduce((acc, cur) => {
        acc[cur.ruleName] = (acc[cur.ruleName] || 0) + 1;
        return acc;
    }, {});
}

function generateHtmlOutput(json, summaryInfo) {
    const html = [
        getHeader(`ilib-lint Result for webOS Apps`),
        getHtmlStyle(),
        getScript("rule-filter.js"),
        getSummary(json.summary),
        getRules(json.rules),
        getDetailResults(json.details, errorsOnly),
        getFooter()
    ].join('');

    const resultFile = options.outputFileName ||
        `${json.summary.projectName}-result.html`;

    const finalPath = path.join(outDir, resultFile);
    const dirPath = path.dirname(finalPath);

    if (!fs.existsSync(dirPath)) {
        fs.mkdirSync(dirPath, { recursive: true });
    }

    fs.writeFileSync(finalPath, html, 'utf8');
}

/* ----------------------------------------
 * HTML Formatting Helpers
 * --------------------------------------*/
function getSummary(summary) {
    const fmt = new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 });
    const ratio = num => [
        fmt.format(num / summary.fileStats.files),
        fmt.format(num / summary.fileStats.modules),
        fmt.format(num / summary.fileStats.lines),
    ];
    const [errFile, errMod, errLine] = ratio(summary.resultStats.errors);
    const [warnFile, warnMod, warnLine] = ratio(summary.resultStats.warnings);
    const [sgFile, sgMod, sgLine] = ratio(summary.resultStats.suggestions);

    return `
<body>
<h1>[${escapeHtml(summary.projectName)}] Summary</h1><hr>
<table>
  <thead>
    <tr>
      <td></td><td>Total</td><td>${summary.fileStats.files} Files</td>
      <td>${summary.fileStats.modules} Modules</td>
      <td>${summary.fileStats.lines} Lines</td>
    </tr>
    <tr><td class="highlight">Errors:</td><td class="red">${summary.resultStats.errors}</td><td>${errFile}</td><td>${errMod}</td><td>${errLine}</td></tr>
    <tr><td class="highlight">Warnings:</td><td class="orange">${summary.resultStats.warnings}</td><td>${warnFile}</td><td>${warnMod}</td><td>${warnLine}</td></tr>
    <tr><td class="highlight">Suggestions:</td><td>${summary.resultStats.suggestions}</td><td>${sgFile}</td><td>${sgMod}</td><td>${sgLine}</td></tr>
    <tr><td class="highlight">I18N Score</td><td>${fmt.format(summary.score)}</td></tr>
  </thead>
</table><hr>`;
}

function getDetailResults(details, onlyErrors) {
    if (!Array.isArray(details) || details.length === 0) return '';

    const rows = details
        .filter(item => !onlyErrors || item.severity === 'error')
        .map(formatDetailResult)
        .join('');

    return rows ? `<div id="detail-section"><h2>Detailed Information</h2>${rows}</div>` : '';
}

function formatDetailResult(res) {
    const color =
        res.severity === 'error'
            ? 'color:white;background-color:maroon;'
            : 'color:white;background-color:orange;';

    const targetHighlighted = (res.highlight || '')
        .replace(/<e\d>/g, '<span style="color:red">')
        .replace(/<\/e\d>/g, '</span>');

    const autofix = res?.fix?.applied || 'unavailable';

    return `
<table>
<thead><tr><th colspan="2" style="${color}">${escapeHtml(res.severity.toUpperCase())}</th></tr></thead>
<tbody>
  <tr><td>filepath</td><td>${escapeHtml(res.path)}</td></tr>
  <tr><td>Description</td><td>${escapeHtml(res.description)}</td></tr>
  <tr><td>key</td><td>${escapeHtml(res.key)}</td></tr>
  <tr><td>source</td><td>${escapeHtml(res.source)}</td></tr>
  <tr><td>target</td><td>${targetHighlighted}</td></tr>
  <tr><td>rule</td><td>${escapeHtml(res.ruleName)}</td></tr>
  <tr><td>rule Description</td><td>${escapeHtml(res.description)}</td></tr>
  <tr><td>More info</td><td><a href="${escapeHtml(res.link)}">${escapeHtml(res.link)}</a></td></tr>
  <tr><td>Auto-fix</td><td>${escapeHtml(autofix)}</td></tr>
</tbody>
</table>`;
}

function getRules(rules) {
    if (!Array.isArray(rules) || rules.length === 0) return '';
    let contents = '<h2>rules</h2><button id="select-all">Select All</button><button id="unselect-all">Deselect All</button><table><thead>';
    rules.forEach(item => {
        contents += `<tr><td class="highlight"><label><input type="checkbox" class="rule-check" value="${escapeHtml(item)}">${escapeHtml(item)}</label></td></tr>`;
    });
    contents += '</thead></table>';
    return contents;
}

function getHeader(title) {
    return `<!DOCTYPE html><html><head><title>${escapeHtml(title)}</title><meta charset="UTF-8"></head>`;
}

function getFooter() {
    return `</body></html>`;
}

function getScript(filename) {
    if (!filename) return;
    const scriptCode = fs.readFileSync(path.join(process.cwd(), "convertHtml", filename), "utf8");
    return `<script>\n${scriptCode}\n</script>`;
}

function getHtmlStyle() {
    const styleCode = fs.readFileSync(path.join(process.cwd(), "convertHtml", "style.css"), "utf8");
    return `<style>\n${styleCode}\n</style>`;
}
