#!/usr/bin/env node
/*
 * convertHtml.js - converts JSON files generated by webOSJsonFormatter
 *               into HTML reports and produces an overall Total Summary page.
 *
 * Copyright (c) 2026 JEDLSoft
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import path from 'node:path';
import fs from 'fs';
import OptionsParser from 'options-parser';

// Constants
const DEFAULT_OUTPUT_DIR = './';
const TOTAL_RESULT_FILENAME = '0.total-result.html';

// Rule descriptions — add or update entries here manually
const RULE_DESCRIPTIONS = {
    'resource-named-params': { text: 'Ensure that named parameters that appear in the source string are also used in the translated string.', link: 'https://github.com/iLib-js/ilib-mono/blob/main/packages/ilib-lint/docs/resource-named-params.md' },
    'resource-completeness': { text: 'Ensure that all resources in your project have either a source or target element defined', link: 'https://github.com/iLib-js/ilib-mono/blob/main/packages/ilib-lint/docs/resource-completeness.md' },
    'resource-url-match': { text: 'Ensure that URLs that appear in the source string are also used in the translated string.', link: 'https://github.com/iLib-js/ilib-mono/blob/main/packages/ilib-lint/docs/resource-url-match.md' },
    'resource-edge-whitespace': { text: 'Ensure that the whitespace at the edges of the target string exactly matches that of the source string, both at the beginning and at the end.', link: 'https://github.com/iLib-js/ilib-mono/blob/main/packages/ilib-lint/docs/resource-edge-whitespace.md' },
};

// Option configuration
const optionConfig = {
    files: {
        short: 'f',
        varName: 'f',
        help: 'Specify files'
    },
    directory: {
        short: 'd',
        varName: 'directory',
        help: 'Directory where JSON files are located'
    },
    outputDirectory: {
        short: 'o',
        varName: 'output folder',
        help: 'Folder where output HTML files will be generated.'
    },
    outputFileName: {
        short: 'name',
        varName: 'output file name',
        help: 'Specify output HTML file name'
    },
    errorsOnly: {
        short: 'e',
        flag: true,
        default: false,
        help: 'Only return errors and suppress warnings'
    },
    version: {
        varName: 'version label',
        help: 'Submission label displayed at the top of the HTML report'
    }
};

// Parse options
const options = OptionsParser.parse(optionConfig).opt;
const errorsOnly = options.errorsOnly ?? false;
const outDir = options.outputDirectory || DEFAULT_OUTPUT_DIR;
const version = options.version || '';

let totalSummary = [];

// Ensure output directory exists
ensureOutputDirectory(outDir);

// Entry point
if (options.files) console.log("File input is not implemented yet.");
if (options.directory) processDirectory(options.directory);

/* ----------------------------------------
 * HTML Escape Helper
 * --------------------------------------*/
function escapeHtml(str) {
    if (typeof str !== 'string') return str;
    return str
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#39;");
}

/* ----------------------------------------
 * Directory Processing
 * --------------------------------------*/
function ensureOutputDirectory(directory) {
    if (!fs.existsSync(directory)) {
        fs.mkdirSync(directory, { recursive: true });
    }
}

function processDirectory(dir) {
    try {
        const stat = fs.statSync(dir);
        if (!stat.isDirectory()) throw new Error("Invalid directory");
        walkDirectory(dir);
        writeTotalSummaryResult(totalSummary);
    } catch (err) {
        console.error(`Directory error: ${err.message}`);
        process.exit(1);
    }
}

function walkDirectory(dir) {
    const files = fs.readdirSync(dir);
    for (const file of files) {
        const fullPath = path.join(dir, file);
        if (fullPath.includes(".git")) continue;
        const stat = fs.statSync(fullPath);
        if (stat.isDirectory()) {
            walkDirectory(fullPath);
        } else if (file.toLowerCase().endsWith('.json')) {
            convertToHtml(fullPath);
        }
    }
}

/* ----------------------------------------
 * HTML Summary Generation
 * --------------------------------------*/
function writeTotalSummaryResult(sumJsonData) {
    const sorted = [...sumJsonData].sort((a, b) => a.name.localeCompare(b.name));
    const html = [
        getHeader("Summary of all app results"),
        getHtmlStyle(),
        getScript("case-filter.js"),
        buildTotalSummaryTable(sorted),
        getFooter()
    ].join('');

    fs.writeFileSync(path.join(outDir, "total-result.json"), JSON.stringify(sorted, null, 2), 'utf8');
    fs.writeFileSync(path.join(outDir, TOTAL_RESULT_FILENAME), html, 'utf8');
}

function buildTotalSummaryTable(data) {
    let count = 0;
    const totalErrors = data.reduce((sum, item) => sum + item.errors, 0);
    const totalWarnings = data.reduce((sum, item) => sum + item.warnings, 0);
    const appsWithIssues = data.filter(item => item.errors > 0 || item.warnings > 0).length;

    const ruleTotal = data.reduce((acc, item) => {
        if (!item.details) return acc;
        for (const [rule, cnt] of Object.entries(item.details)) {
            acc[rule] = (acc[rule] || 0) + cnt;
        }
        return acc;
    }, {});
    const ruleTotalRows = Object.entries(ruleTotal)
        .sort((a, b) => b[1] - a[1])
        .map(([rule, cnt]) => {
            const entry = RULE_DESCRIPTIONS[rule];
            const ruleName = entry?.link
                ? `<a href="${escapeHtml(entry.link)}" target="_blank">${escapeHtml(rule)}</a>`
                : escapeHtml(rule);
            const desc = entry ? escapeHtml(entry.text ?? entry) : '';
            return `
    <tr>
      <td class="col-rule">${ruleName}</td>
      <td class="col-count">${cnt}</td>
      <td class="col-desc">${desc}</td>
    </tr>`;
        }).join('');

    const rows = data.map(item => {
        const ruleInfo = buildRuleInfo(item.details);
        const nameColumn =
            item.errors === 0 && item.warnings === 0
                ? escapeHtml(item.name)
                : `<a href="./${escapeHtml(item.name)}-result.html">${escapeHtml(item.name)}</a>`;

        const rowClass = (item.errors === 0 && item.warnings === 0) ? 'no-issues' : '';

        return `
        <tr class="${rowClass}">
            <td>${++count}</td>
            <td class="highlight">${nameColumn}</td>
            <td class="red">${item.errors}</td>
            <td class="orange">${item.warnings}</td>
            <td>${ruleInfo}</td>
        </tr>`;
    }).join('');

    return buildPageHeader('Summary of all app results') + `
  <div class="stat-cards">
    <div class="stat-card errors">
      <div class="stat-label">Total Errors</div>
      <div class="stat-value">${totalErrors}</div>
    </div>
    <div class="stat-card warnings">
      <div class="stat-label">Total Warnings</div>
      <div class="stat-value">${totalWarnings}</div>
    </div>
    <div class="stat-card total">
      <div class="stat-label">Total Issues</div>
      <div class="stat-value">${totalErrors + totalWarnings}</div>
    </div>
    <div class="stat-card apps-with-issues">
      <div class="stat-label">Apps with Issues</div>
      <div class="stat-value">${appsWithIssues} <span class="stat-total">/ ${data.length}</span></div>
    </div>
  </div>
  <div class="card">
    <h2>Issues by Rule</h2>
    <table>
      <thead><tr><th class="col-rule">Rule</th><th class="col-count">Count</th><th class="col-desc">Description</th></tr></thead>
      <tbody>${ruleTotalRows}</tbody>
    </table>
  </div>
  <div class="card">
    <label><input type="checkbox" id="toggleNoIssues"> Show only cases with errors/warnings</label>
    <table>
      <thead><tr><th>#</th><th>Name</th><th>Errors</th><th>Warnings</th><th>Details</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
  </div>`;
}


function buildPageHeader(title) {
    const sub = version
        ? `<p class="version-label">${escapeHtml(version)}</p>`
        : '';
    return `
<body>
<div class="page-header">
  <h1>${escapeHtml(title)}</h1>${sub}
</div>
<div class="page-wrapper">`;
}

function buildRuleInfo(details) {
    if (!details) return '';
    return Object.entries(details)
        .map(([rule, count]) => `${escapeHtml(rule)} [ ${count} ]<br>`)
        .join('');
}

/* ----------------------------------------
 * JSON → Individual HTML Generator
 * --------------------------------------*/
function convertToHtml(jsonFile) {
    try {
        const json = JSON.parse(fs.readFileSync(jsonFile, 'utf-8'));
        const summary = createSummaryInfo(json.summary);

        if (json.summary.score !== 100) summary.details = countRuleViolations(json.details);

        totalSummary.push(summary);
        generateHtmlOutput(json, summary);

    } catch (err) {
        console.error(`Error in ${jsonFile}: ${err.message}`);
    }
}

function createSummaryInfo(summary) {
    return {
        name: summary.projectName,
        errors: summary.resultStats.errors,
        warnings: summary.resultStats.warnings
    };
}

function countRuleViolations(details) {
    return details.reduce((acc, cur) => {
        acc[cur.ruleName] = (acc[cur.ruleName] || 0) + 1;
        return acc;
    }, {});
}

function generateHtmlOutput(json, summaryInfo) {
    const html = [
        getHeader(`ilib-lint Result for webOS Apps`),
        getHtmlStyle(),
        getScript("rule-filter.js"),
        getSummary(json.summary),
        getRules(json.rules),
        getDetailResults(json.details, errorsOnly),
        getFooter()
    ].join('');

    const resultFile = options.outputFileName ||
        `${json.summary.projectName}-result.html`;

    const finalPath = path.join(outDir, resultFile);
    const dirPath = path.dirname(finalPath);

    if (!fs.existsSync(dirPath)) {
        fs.mkdirSync(dirPath, { recursive: true });
    }

    fs.writeFileSync(finalPath, html, 'utf8');
}

/* ----------------------------------------
 * HTML Formatting Helpers
 * --------------------------------------*/
function getSummary(summary) {
    const fmt = new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 });
    const ratio = num => [
        fmt.format(num / summary.fileStats.files),
        fmt.format(num / summary.fileStats.modules),
        fmt.format(num / summary.fileStats.lines),
    ];
    const [errFile, errMod, errLine] = ratio(summary.resultStats.errors);
    const [warnFile, warnMod, warnLine] = ratio(summary.resultStats.warnings);

    return buildPageHeader(`[${summary.projectName}] Summary`) + `
  <div class="stat-cards">
    <div class="stat-card errors">
      <div class="stat-label">Errors</div>
      <div class="stat-value">${summary.resultStats.errors}</div>
    </div>
    <div class="stat-card warnings">
      <div class="stat-label">Warnings</div>
      <div class="stat-value">${summary.resultStats.warnings}</div>
    </div>
  </div>
  <div class="card">
    <h2>Breakdown</h2>
    <table>
      <thead>
        <tr>
          <th></th><th>Total</th><th>${summary.fileStats.files} Files</th>
          <th>${summary.fileStats.modules} Modules</th><th>${summary.fileStats.lines} Lines</th>
        </tr>
      </thead>
      <tbody>
        <tr><td class="highlight">Errors</td><td class="red">${summary.resultStats.errors}</td><td>${errFile}</td><td>${errMod}</td><td>${errLine}</td></tr>
        <tr><td class="highlight">Warnings</td><td class="orange">${summary.resultStats.warnings}</td><td>${warnFile}</td><td>${warnMod}</td><td>${warnLine}</td></tr>

      </tbody>
    </table>
  </div>`;
}

function getDetailResults(details, onlyErrors) {
    if (!Array.isArray(details) || details.length === 0) return '';

    const rows = details
        .filter(item => !onlyErrors || item.severity === 'error')
        .map(formatDetailResult)
        .join('');

    return rows ? `<div id="detail-section" class="card"><h2>Detailed Information</h2>${rows}</div>` : '';
}

function formatDetailResult(res) {
    const color =
        res.severity === 'error'
            ? 'color:white;background-color:#e53e3e;'
            : 'color:white;background-color:#dd6b20;';

    const targetHighlighted = (res.highlight || '')
        .replace(/<e\d>/g, '<span style="color:red">')
        .replace(/<\/e\d>/g, '</span>');

    const autofix = res?.fix?.applied || 'unavailable';

    return `
<table>
<thead><tr><th colspan="2" style="${color}">${escapeHtml(res.severity.toUpperCase())}</th></tr></thead>
<tbody>
  <tr><td>filepath</td><td>${escapeHtml(res.path)}</td></tr>
  <tr><td>Description</td><td>${escapeHtml(res.description)}</td></tr>
  <tr><td>key</td><td>${escapeHtml(res.key)}</td></tr>
  <tr><td>source</td><td>${escapeHtml(res.source)}</td></tr>
  <tr><td>target</td><td>${targetHighlighted}</td></tr>
  <tr><td>rule</td><td>${escapeHtml(res.ruleName)}</td></tr>
  <tr><td>rule Description</td><td>${escapeHtml(res.description)}</td></tr>
  <tr><td>More info</td><td><a href="${escapeHtml(res.link)}">${escapeHtml(res.link)}</a></td></tr>
  <tr><td>Auto-fix</td><td>${escapeHtml(autofix)}</td></tr>
</tbody>
</table>`;
}

function getRules(rules) {
    if (!Array.isArray(rules) || rules.length === 0) return '';
    let rows = '';
    rules.forEach(item => {
        rows += `<tr><td><label><input type="checkbox" class="rule-check" value="${escapeHtml(item)}">${escapeHtml(item)}</label></td></tr>`;
    });
    return `
<div class="card">
  <h2>Rules</h2>
  <button id="select-all">Select All</button><button id="unselect-all" class="secondary">Deselect All</button>
  <table class="compact"><tbody>${rows}</tbody></table>
</div>`;
}

function getHeader(title) {
    return `<!DOCTYPE html><html><head><title>${escapeHtml(title)}</title><meta charset="UTF-8"></head>`;
}

function getFooter() {
    return `</div></body></html>`;
}

function getScript(filename) {
    if (!filename) return;
    const scriptCode = fs.readFileSync(path.join(process.cwd(), "convertHtml", filename), "utf8");
    return `<script>\n${scriptCode}\n</script>`;
}

function getHtmlStyle() {
    const styleCode = fs.readFileSync(path.join(process.cwd(), "convertHtml", "style.css"), "utf8");
    return `<style>\n${styleCode}\n</style>`;
}
